name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Update to v3
      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./  # Directory to publish
          publish_branch: gh-pages  # Specify the branch to publish to
          github_token: ${{ secrets.GITHUB_TOKEN }}  # Use the GitHub token for authentication
          allow_empty_commit: false
          keep_files: false
          force_orphan: false
          enable_jekyll: false
          disable_nojekyll: false
          exclude_assets: .github
